import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar/navbar";

// Define Co Headline fonts
const coHeadlineRegular = localFont({
  src: "./fonts/Co-headline.woff",
  variable: "--font-co-headline-regular",
});

const coHeadlineLight = localFont({
  src: "./fonts/Co-headline-Light.woff",
  variable: "--font-co-headline-light",
});

const coHeadlineBold = localFont({
  src: "./fonts/Co-headline-Bold.woff",
  variable: "--font-co-headline-bold",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${coHeadlineRegular.variable} ${coHeadlineLight.variable} ${coHeadlineBold.variable}`}
      >
        <div className="container">
          <div className="wrapper">
            <Navbar>{children}</Navbar>
          </div>
        </div>
      </body>
    </html>
  );
}
